/* Automatically generated by './build/bin/build-entry.js' */

import sccCanvas from './components/canvas/index.js';
import sccCol from './components/col/index.js';
import sccRow from './components/row/index.js';

const components = [
  sccCanvas,
  sccCol,
  sccRow
];

const install = function(Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component)
  });
};

if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '1.3.27',
  install,
  sccCanvas,
  sccCol,
  sccRow
};
